config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :accessories
  resources :rooms
  resources :buildings
  resources :users
  get '/occupancy', to: 'rooms#occupancy'
  get '/charts', to: 'reservations#charts'
  get '/all_reservations', to: 'reservations#all'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new' 
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  post '/schedule', to: 'reservations#schedule' 
  post '/reserve', to: 'reservations#reserve' 
  post '/switch_role', to: 'users#switch_role' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 90 } 
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
	validates :password, presence: true, length: { minimum: 8 } 
	has_secure_password
	has_many :reservations, dependent: :destroy
	has_many :rooms, through: :reservations

	def is_admin? 
		self.admin
	end

	def switch_role
		role = self.admin
		self.update_attribute("admin", !role)
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :switch_role]
  before_action :verify_if_admin_and_redirect_with_error_message_if_not, only: [:index, :destroy, :switch_role]
	skip_before_action :logged_in_user, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users_selected_in_nav = true
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if (@user.email != current_user.email && !current_user.admin?)
      flash[:danger] = "You are not authorized to see other users information."
      redirect_to current_user
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if !current_user.is_admin? && (@user.email != current_user.email)
      flash[:warning] = "A user can only modify their own data."
      redirect_to @user
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
			if @user.save
				log_in @user unless logged_in?
        flash[:success] = "User was successfully created."
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:danger] = "There was an error performing the operation. #{@user.errors.full_messages.first}"
        format.html { redirect_back fallback_location: users_path}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    params[:user].delete(:admin) if current_user == @user
    #params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "User information was successfully updated."
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        flash[:danger] = "There was an error performing the operation. #{@user.errors.full_messages.first}"
        format.html { redirect_back fallback_location: @user }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if (@user == current_user)
      flash[:danger] = "You are not allowed to delete your own user."
      redirect_to current_user
    else
      @user.destroy
      respond_to do |format|
        flash[:success] = "User was successfully deleted."
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    end
  end

  def switch_role
    respond_to do |format|
      if @user.switch_role
        flash[:success] = "User role was successfully updated. Admin role is now: #{@user.admin}"
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        flash[:danger] = "There was an error performing the operation. #{@user.errors.full_messages.first}"
        format.html { redirect_back fallback_location: @user }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      begin 
        @user = User.find(params[:id])
      rescue 
        flash[:danger] = "There was an error performing the operation."
        redirect_back fallback_location: current_user
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
    end

    def verify_if_admin_and_redirect_with_error_message_if_not 
      unless current_user.is_admin?
        flash[:danger] = "You are not authorized to perform this action."
        redirect_to current_user
      end 
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
  </div>
  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
  </div>
  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password %><br>
  </div>
  <div class="field">
    <%= form.label :password_confirmation, "Confirmation" %><br>
    <%= form.password_field :password_confirmation %><br>
  </div>
  <% if logged_in? && current_user.is_admin? %>
    <br>
    <div class="field">
      <%= form.label :admin %>
    <% if current_user == user %>
        <%= form.check_box :admin, disabled: true %><br>
    <% else %>
        <%= form.check_box :admin %><br>
    <% end %>
    </div>
  <% end %><br>
  <div class="actions" style="float:right">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="col"> 
      <div class="card" style="width:290px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <h3 style="text-align:center">Edit user info</h3>
        </div>
        <div class="card-body">
          <div class="container">
            <%= render 'form', user: @user %>
          </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <%= link_to "Back", @user, class: 'btn btn-sm btn-secondary'%>
</div>

app/views/users/index.html.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:950px; text-align:center"><b>Registered users</b></h5>
<div class="container" style="width:950px;">
  <div class="row">
    <% @users.each do |user| %>
      <a href="users/<%= user.id %>" style="text-decoration:none; color:#bce5ff; margin:0 auto;">
        <div class="card" style="width:300px; margin-bottom:10px">
          <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
            <h4 style="text-align:center"><strong><%= user.name %></strong></h4>
          </div>
          <div class="card-body" style="margin-left:15px">
            <div>Email: <strong><%= user.email %></strong></div>
            <div>Role: 
            <% if user.admin %>
              <strong><font color="#728C00"> Admin</font></strong>
            <% else %>
              <strong><font color="#2B547E">User</font></strong>
            <% end %></div>
          </div>
        </div>
      </a>
    <% end %>
  </div><br><br>
  <% if current_user.is_admin? %>
    <%= link_to 'New User', new_user_path, :class => "btn btn-sm btn-success" %>
  <% end %>
</div><br>

app/views/users/new.html.erb
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="col"> 
      <div class="card" style="width:290px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <h3 style="text-align:center">New user</h3>
        </div>
        <div class="card-body">
          <div class="container">
            <%= render 'form', user: @user %>
          </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <%= link_to "Back", users_path, class: 'btn btn-sm btn-secondary'%>
</div>

app/views/users/show.html.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:1000px; text-align:center"><b>User details</b></h5>
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="col">
      <div class="card" style="width:550px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
            <h3 style="text-align:center"><strong><%= @user.name %></strong></h3>
        </div>
        <div class="card-body">
          <div class="container">
            <div class="row">
              <div class="col">
                Email: <strong><%= @user.email %></strong>
              </div>
              <div class="col">
                Administrator role: <strong><font color="yellow"><%= @user.admin %></font></strong>
              </div>
            </div><br>
            <div class="row" style="float:right">
              <% if current_user == @user %>
                <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-sm btn-info'  %>
              <% elsif current_user.is_admin? %>
                <%= form_with scope: :users, url: switch_role_path do |f| %>
                  <%= hidden_field_tag(:id, @user.id) %>
                  <%= f.submit "Switch role", data: { confirm: 'The user role will be changed: Are you sure?' }, class: 'btn btn-sm btn-warning' %>
                <% end %> &nbsp;
                <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <% if current_user.is_admin? %>
      <%= link_to 'Users list', users_path, class: 'btn btn-sm btn-primary' %>
  <% end %>
</div>