config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :accessories
  resources :rooms
  resources :buildings
  resources :users
  get '/occupancy', to: 'rooms#occupancy'
  get '/charts', to: 'reservations#charts'
  get '/all_reservations', to: 'reservations#all'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new' 
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  post '/schedule', to: 'reservations#schedule' 
  post '/reserve', to: 'reservations#reserve' 
  post '/switch_role', to: 'users#switch_role' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :rooms, dependent: :destroy
    validates :name, presence: true, uniqueness: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]
  before_action :verify_if_admin_and_redirect_with_error_message_if_not, only: [:new, :edit, :create, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings_selected_in_nav = true
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        flash[:success] = "Building was successfully created."
        format.html { redirect_to @building }
        format.json { render :show, status: :created, location: @building }
      else
        flash[:danger] = "There was an error performing the operation. #{@building.errors.full_messages.first}"
        format.html { redirect_back fallback_location: buildings_path }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        flash[:success] = "Building information was successfully updated."
        format.html { redirect_to @building }
        format.json { render :show, status: :ok, location: @building }
      else
        flash[:danger] = "There was an error performing the operation. #{@building.errors.full_messages.first}"
        format.html { redirect_back fallback_location: @building }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  # def destroy
  #   @building.destroy
  #   respond_to do |format|
  #     flash[:success] = "Building was successfully deleted."
  #     format.html { redirect_to buildings_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name, :address, :coordinates)
    end

    def verify_if_admin_and_redirect_with_error_message_if_not 
      unless current_user.is_admin?
        flash[:danger] = "You are not authorized to perform this action."
        redirect_to buildings_url
      end 
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </div>
  <div class="field">
    <%= form.label :coordinates %><br>
    <%= form.text_field :coordinates %>
  </div>
  <br><br>
  <div class="actions" style="float:right">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="col"> 
      <div class="card" style="width:285px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <h3 style="text-align:center">Edit building info</h3>
        </div>
        <div class="card-body">
          <div class="container">
            <%= render 'form', building: @building %>
          </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <%= link_to "Back", @building, class: 'btn btn-sm btn-secondary'%>
</div>

app/views/buildings/index.html.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:1080px; text-align:center"><b>Buildings</b></h5>
<div class="container" style="width:1080px;">
  <div class="row">
    <% @buildings.each do |building| %>
      <div class="card" style="width:350px; margin-bottom:8px; margin:0 auto;">
        <a href="buildings/<%= building.id %>" style="text-decoration:none; color:#bce5ff;">
          <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
            <h3 style="text-align:center"><strong><%= building.name %></strong></h3>
          </div>
        </a>
        <div class="card-body">
          <div>Address: <strong><%= building.address %></strong></div>
          <div>Coordinates: <strong><%= building.coordinates %></strong></div><br>
          <div>Available rooms: 
            <a href="/rooms?building_id=<%= building.id %>">
              <strong><font color="yellow"><%= building.rooms.where(active: true).count %></font></strong>
            </a>
          </div>
        </div>
      </div>
    <% end %>
  </div><br><br>
  <div class="row">
    <div class="col">
      <% if current_user.is_admin? %>
        <div class="row">
          <%= link_to 'New Building', new_building_path, :class => "btn btn-sm btn-success" %> &nbsp;
        </div>
      <% end %>
    </div>
  </div>
</div><br>

app/views/buildings/new.html.erb
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="col"> 
      <div class="card" style="width:285px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <h3 style="text-align:center">New building</h3>
        </div>
        <div class="card-body">
          <div class="container">
            <%= render 'form', building: @building %>
          </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <%= link_to "Back", buildings_path, class: 'btn btn-sm btn-secondary'%>
</div>

app/views/buildings/show.html.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:1000px; text-align:center"><b>Building details</b></h5>
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="card" style="width:350px">
      <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <h3 style="text-align:center"><strong><%= @building.name %></strong></h3>
      </div>
      <div class="card-body">
        <div>Address: <strong><%= @building.address %></strong></div>
        <div>Coordinates: <strong><%= @building.coordinates %></strong></div><br>
        <div>Rooms: 
          <a href="/rooms?building_id=<%= @building.id %>">
            <strong><font color="yellow"><%= @building.rooms.where(active: true).count %></font></strong>
          </a>
        </div>
        <% if current_user.is_admin? %>
          <div style="float:right">
            <%= link_to 'Edit', edit_building_path(@building), class: 'btn btn-sm btn-info' %>
            <%#= link_to 'Delete', @building, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div><br><br>
  <%= link_to 'Buildings list', buildings_path, class: 'btn btn-sm btn-primary' %>
</div>