config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :accessories
  resources :rooms
  resources :buildings
  resources :users
  get '/occupancy', to: 'rooms#occupancy'
  get '/charts', to: 'reservations#charts'
  get '/all_reservations', to: 'reservations#all'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new' 
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  post '/schedule', to: 'reservations#schedule' 
  post '/reserve', to: 'reservations#reserve' 
  post '/switch_role', to: 'users#switch_role' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  validates :valid_to, presence: true
  validates :valid_from, presence: true
  before_save :auto_complete_duration
  scope :scheduled, -> {where("valid_from > ?", Time.current)}
  scope :active, -> {where("valid_from <= ? AND valid_to >= ?", Time.current, Time.current)}
  scope :expired, -> {where("valid_to < ?", Time.current)}
  scope :not_expired, ->{where("valid_to > ?", Time.current)}
  scope :business_hours, -> {where("cast(strftime('%H', valid_from) as int) IN (?) AND cast(strftime('%H', valid_to) as int) IN (?)", (9..17), (9..18))}
  scope :last_week, -> {where("date(valid_from) >= ? AND date(valid_to) < ?", Date.today - 1.week, Date.today)}
  scope :last_month, -> {where("date(valid_from) >= ? AND date(valid_to) < ?", Date.today - 1.month, Date.today)}
  validate :period
  validate :period_overlaps

  def period
    errors.add(:reservation, "'Start time' cannot be in the past.") if self.valid_from.past?
    errors.add(:reservation, "'End time' cannot be in the past.") if !(self.valid_from < self.valid_to)
    errors.add(:reservation, "Reservations are only allowed from Mondays to Fridays") if (self.valid_from.on_weekend?)||(self.valid_to.on_weekend?)
    errors.add(:reservation, "Reservations are only allowed from 9am to 6pm.") if ((self.valid_from.hour < 9)||(self.valid_to.hour > 18)||(self.valid_to.hour == 18 && self.valid_to.min > 0))
  end

  def period_overlaps
    is_overlapping = Reservation.where(room: room).any? do |r|
      (r.valid_from...r.valid_to).overlaps?(self.valid_from...self.valid_to)
    end
    errors.add(:reservation, "There is an active reservation for this Room in the specified period.") if is_overlapping
  end

  def self.reserved_in(time)
    where("cast(strftime('%H', valid_from) as int) <= ? AND cast(strftime('%H', valid_to) as int) >= ?", time, time)
  end


  private

  def auto_complete_duration
    self.duration = ((self.valid_to - self.valid_from) / 3600).round(2)
  end

end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :building
	has_and_belongs_to_many :accessories
	has_many :reservations
	has_many :users, through: :reservations
	validates :name, presence: true
	validates :code, uniqueness: true
	paginates_per 15

	def is_active?
		self.active
	end

	def status
		response = Faraday.get "https://ca-3-api.mybluemix.net/api/v1/rooms/#{self.code}"
		#response.body
		output = case
			when response.status == 200 then JSON.parse(response.body)
			when response.status == 404 then nil
		end
	end	

	def self.without_active_reservation
		Room.all - Room.joins(:reservations).merge(Reservation.active)
	end

	def drop_down
		"#{self.name} - Floor: #{self.floor} - Max. capacity: #{self.max_capacity} - Equipment: #{self.accessories.map{|a| a.name}}"
	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_room, only: [:new, :create]
  before_action :verify_if_active_and_redirect_with_error_message_if_not, only: [:new, :create]
  before_action :verify_if_admin_and_redirect_with_error_message_if_not, only: [:all, :charts]

  def index
    @reservations_selected_in_nav = true
  end

  def show
    begin 
      @reservation = Reservation.find(params[:id])
      unless (current_user.is_admin? || current_user == @reservation.user)
        flash[:danger] = "You are not authorized to perform this action."
        redirect_to reservations_url
      end 
      @room = @reservation.room
      if (@reservation.attendants? && @room.max_capacity? && @reservation.attendants > @room.max_capacity)
        flash.now[:warning] = "Take into consideration that there might not be enough sits for all attendants."
      end
    rescue 
      flash[:danger] = "Reservation not found"
      redirect_to all_reservations_url
    end
  end

  def new
    @reservation = Reservation.new
    if current_user.reservations.active.where(room_id: @room.id).exists?
      flash.now[:info] = "You already have an active reservation on this room 
      from: #{current_user.reservations.active.find_by(room_id: @room.id).valid_from} 
      to: #{current_user.reservations.active.find_by(room_id: @room.id).valid_to}"
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.room = @room
    @reservation.user = current_user

    if @reservation.save
      flash[:success] = "You have successfully reserved room '#{@room.name}'."
      redirect_to @reservation
    else
      flash[:danger] = "There was an error performing the operation. #{@reservation.errors.messages.first.last.first}"
      redirect_back fallback_location: rooms_path
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id]).destroy
    respond_to do |format|
      flash[:success] = "Reservation was successfully canceled."
      format.html { redirect_back fallback_location: reservations_url }
      format.json { head :no_content }
    end
  end

  def all
    @reservations_selected_in_nav = true
    @reservations = Reservation.all
  end

  def charts
    @charts_selected_in_nav = true

    #Percentage of time reserved per room per day [Last week]
    @chart1 = Room
    .joins(:reservations)
    .merge(Reservation.last_week.business_hours)
    .group(:name)
    .group("date(valid_from)")
    .sum(:duration)
    .map{|k,v| [k,(v/9*100).round(2)]}.to_h

    #Percentage of rooms reserved per hour [Last month]
    @chart2 = {}
    for i in (9..18)
      @chart2["#{i}:00"] = ((Reservation
      .last_month
      .business_hours
      .reserved_in(i)
      .group(:room_id)
      .count.count)
      .to_f * 100/Room.count).round(2)
    end

    #Users with more reservations [Last month]
    @chart3 = User
    .joins(:reservations)
    .merge(Reservation.last_month)
    .group(:name)
    .order('count_id desc')
    .count('id')
    .take(5)

    #Rooms with more reservations [Last month]
    @chart4 = Room
    .joins(:reservations)
    .merge(Reservation.last_month)
    .group(:name)
    .order('count_id desc')
    .count('id')
    .take(5)
  end

  def schedule
    @building_id = params[:reservation][:building_id].to_i
    @attendants = params[:reservation][:attendants].to_i
    #@equipment = params[:reservation][:accessory_ids]
    params[:reservation].delete(:building_id)
    #params[:reservation].delete(:accessory_ids)
    @reservation = Reservation.new(reservation_params)
    @rooms = Room
    .where(active: true)
    .where(building_id: @building_id)
    .where("max_capacity >= ?", @attendants)
    #.joins(:accessories)
    #.where("accessory_id IN (?)", @equipment) #must be fixed to include only rooms with required equipment
    ##add additional queries to filter for rooms without reservations in the selected timeframe
    render "static_pages/home"
  end
  
  def reserve
    @reservation = Reservation.new
    @reservation.valid_from = params[:valid_from]
    @reservation.valid_to = params[:valid_to]
    @reservation.attendants = params[:attendants]
    @reservation.room_id = reservation_params[:room_id].to_i
    @reservation.user = current_user

    if @reservation.save
      flash[:success] = "You have successfully reserved room '#{@reservation.room.name}'."
      redirect_to @reservation
    else
      flash[:danger] = "There was an error performing the operation. #{@reservation.errors.messages.first.last.first}"
      redirect_to :controller => 'static_pages', :action => 'home' 
    end
  end
  

  private
  
  def set_room
    @room = Room.find(params[:room_id])
  end

  def reservation_params
    params.require(:reservation).permit(:valid_from, :valid_to, :room_id, :user_id, :active, :attendants)
  end

  def verify_if_active_and_redirect_with_error_message_if_not 
    unless @room.active
      flash[:danger] = "Room '#{@room.name}' is out of service at this moment. Please choose another room."
      redirect_to rooms_url
    end 
  end

  def verify_if_admin_and_redirect_with_error_message_if_not 
    unless current_user.is_admin?
      flash[:danger] = "You are not authorized to perform this action."
      redirect_to reservations_url
    end 
  end
  
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_reserve_form.html.erb
<%= form_with scope: :reservation, url: reserve_path do |form| %>
  <%= hidden_field_tag(:building_id, @building) %>
  <%= hidden_field_tag(:attendants, @attendants) %>
  <%= hidden_field_tag(:valid_from, @reservation.valid_from) %>
  <%= hidden_field_tag(:valid_to, @reservation.valid_to) %>
  
  <div class="field">
    <%= form.collection_select(:room_id, @rooms, :id, :drop_down) %>
  </div><br>
  <div class="actions" style="float:right">
    <%= form.submit "Reserve", class: 'btn btn-sm btn-success' %>
  </div>
  <br><br>
<% end %>

app/views/reservations/_rooms_form.html.erb
<%= form_with scope: :reservation, url: reserve_path do |form| %>
  <%= hidden_field_tag(:building_id, @building) %>
  <%= hidden_field_tag(:attendants, @attendants) %>
  <%= hidden_field_tag(:valid_from, @reservation.valid_from) %>
  <%= hidden_field_tag(:valid_to, @reservation.valid_to) %>
  
  <div class="field">
    <%= form.label :room %><br>
    <%= form.collection_select(:room_id, @rooms, :id, :drop_down) %>
  </div>
  <div style="float: right;">
    <%= form.submit "Confirm", class: 'btn btn-sm btn-success' %>
  </div>
  <br><br>
<% end %>

app/views/reservations/_schedule_form.html.erb
<%= form_with scope: :reservation, url: schedule_path do |form| %>
  <div class="row">
    <div class="col-4">
      <%= form.label :building %><br>
      <% if @rooms.blank? %>
        <%= form.collection_select(:building_id, Building.all, :id, :name) %>
      <% else %>
        <%= form.collection_select(:building_id, Building.all, :id, :name, {:selected => @building_id}, { :disabled => "disabled" }) %>
      <% end %>
    </div>
    <div class="col-8">
      <div class="field" style="float:right">
        <%= form.label :start_time%> 
        <% if @rooms.blank? %>
          <%= form.datetime_select :valid_from, default: 1.minute.from_now %>
        <% else %>
          <%= form.datetime_select(:valid_from, {:selected => @reservation.valid_from}, { :disabled => "disabled" }) %>
        <% end %>
      </div>
      <div class="field" style="float:right">
        <%= form.label :end_time %> &nbsp;
        <% if @rooms.blank? %>
          <%= form.datetime_select :valid_to, default: 31.minutes.from_now %>
        <% else %>
          <%= form.datetime_select(:valid_to, {:selected => @reservation.valid_to}, { :disabled => "disabled" }) %>
        <% end %>
      </div>
    </div>
  </div><br>
  <div class="row">
    <div class="col-4">
      <div class="field">
        <%= form.label :expected_attendants %><br>
        <% if @rooms.blank? %>
          <%= form.number_field :attendants, min: 0 %>
        <% else %>
          <%= form.number_field :attendants, :value => @reservation.attendants, :disabled => "disabled" %>
        <% end %>  
      </div>
    </div>
    <%# <div class="col-8">
      <div class="check-box checkbox-margin"> &nbsp;
        <%= form.label :required_equipment %><br> &nbsp;
        <%# <%= form.collection_check_boxes(:accessory_ids, Accessory.all, :id, :name) %>
      <%# </div>
    </div> %>
  </div>
  <div class="actions" style="float:right">
    <% if @rooms.blank? %>
      <%= form.submit "Search rooms", class: 'btn btn-sm btn-primary' %>
    <% else %>
      <%= form.submit "Search rooms", :disabled => "disabled", class: 'btn btn-sm btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/reservations/all.html.erb
<h5 class="container" style="width:1100px; background-color: #bce5ff; color:#42698f; opacity:0.7; text-align:center"><b>All active reservations</b></h5>
<table class="table table-striped table-hover" style="width:1100px">
  <thead style="background-color:rgba(0, 151, 255, 0.5)">
    <tr>
      <th style="width:22%;">Room</th>
      <th style="width:22%;">User</th>
      <th style="width:17%;">Reserved from</th>
      <th style="width:17%;">Reserved until</th>
      <th Style="text-align:center;">Action</th>
    </tr>
  </thead>
  <tbody style="background-color:rgba(0, 181, 255, 0.5)">
    <% @reservations.active.sort_by {|item| item.valid_from}.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.room.name, reservation.room, :style => "text-decoration:none; color:#bce5ff;"  %></td>
        <td><%= reservation.user.name %></td>
        <td><%= reservation.valid_from.to_formatted_s(:long) %></td>
        <td><%= reservation.valid_to.to_formatted_s(:long) %></td>
        <td Style="text-align:center;">
          <%= link_to 'Details', reservation, :class => "btn btn-sm btn-info" %>
          <%= link_to 'Cancel Reservation', reservation, method: :delete, :class => "btn btn-sm btn-danger", data: { confirm: 'This reservation will be canceled. Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>
<h5 class="container" style="width:1100px; background-color: #bce5ff; color:#42698f; opacity:0.7; text-align:center"><b>All scheduled reservations</b></h5>
<table class="table table-striped table-hover" style="width:1100px">
  <thead style="background-color:rgba(0, 151, 255, 0.5)">
    <tr>
      <th style="width:22%;">Room</th>
      <th style="width:22%;">User</th>
      <th style="width:17%;">Reserved from</th>
      <th style="width:17%;">Reserved until</th>
      <th Style="text-align:center;">Action</th>
    </tr>
  </thead>
  <tbody style="background-color:rgba(0, 181, 255, 0.5)">
    <% @reservations.scheduled.sort_by {|item| item.valid_from}.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.room.name, reservation.room, :style => "text-decoration:none; color:#bce5ff;"  %></td>
        <td><%= reservation.user.name %></td>
        <td><%= reservation.valid_from.to_formatted_s(:long) %></td>
        <td><%= reservation.valid_to.to_formatted_s(:long) %></td>
        <td Style="text-align:center;">
          <%= link_to 'Details', reservation, :class => "btn btn-sm btn-info" %>
          <%= link_to 'Cancel Reservation', reservation, method: :delete, :class => "btn btn-sm btn-danger", data: { confirm: 'This reservation will be canceled. Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>

app/views/reservations/charts.html.erb
<div class="card">
  <div class="card-header">
    <h3 style="text-align:center">Percentage of time reserved per room per day [Last week]</h3>
  </div>
  <div class="card-body" style="background-color: #C2DFFF; opacity:0.8">
    <%= line_chart @chart1, ytitle: "Reservation", suffix: "%", max: 100 %>
  </div>
</div><br>
<div class="card">
  <div class="card-header">
    <h3 style="text-align:center">Percentage of rooms reserved per hour [Last month]</h3>
  </div>
  <div class="card-body" style="background-color: #C2DFFF; opacity:0.8">
    <%= area_chart @chart2, label: "Rooms reserved", ytitle: "Reservations", suffix: "%", max: 100 %>
  </div>
</div><br>
<div class="card">
  <div class="card-header">
    <h3 style="text-align:center">Users with more reservations [Last month]</h3>
  </div>
  <div class="card-body" style="background-color: #C2DFFF; opacity:0.8">
    <%= column_chart @chart3, label: "Reservations", ytitle: "Reservations" %>
  </div>
</div><br>
<div class="card">
  <div class="card-header">
    <h3 style="text-align:center">Rooms with more reservations [Last month]</h3>
  </div>
  <div class="card-body" style="background-color: #C2DFFF; opacity:0.8">
    <%= bar_chart @chart4, label: "Reservations", xtitle: "Reservations" %>
  </div>
</div><br>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/index.html.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:900px; text-align:center"><b>My scheduled reservations</b></h5>
<table class="table table-striped table-hover" style="width:900px;">
  <thead style="background-color:rgba(0, 151, 255, 0.5)">
    <tr>
      <th style="width:25%;">Room</th>
      <th style="width:22%;">Reserved from</th>
      <th style="width:22%;">Reserved until</th>
      <th Style="text-align:center;">Action</th>
    </tr>
  </thead>
  <tbody style="background-color:rgba(0, 181, 255, 0.5)">
    <% current_user.reservations.not_expired.sort_by {|item| item.valid_from}.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.room.name, reservation.room, :style => "text-decoration:none; color:#bce5ff;" %></td>
        <td><%= reservation.valid_from.to_formatted_s(:long) %></td>
        <td><%= reservation.valid_to.to_formatted_s(:long) %></td>
        <td Style="text-align:center;">
          <%= link_to 'Details', reservation, :class => "btn btn-sm btn-info" %>
          <%= link_to 'Cancel Reservation', reservation, method: :delete, :class => "btn btn-sm btn-danger", data: { confirm: 'This reservation will be canceled. Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table><br><br>
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:900px; text-align:center"><b>My reservations history</b></h5>
<table class="table table-striped table-hover" style="width:900px;">
  <thead style="background-color:rgba(0, 151, 255, 0.5)">
    <tr>
      <th style="width:25%;">Room</th>
      <th style="width:22%;">Reserved from</th>
      <th style="width:22%;">Reserved until</th>
      <th></th>
    </tr>
  </thead>
  <tbody style="background-color:rgba(0, 181, 255, 0.5)">
    <% current_user.reservations.expired.sort_by {|item| item.valid_to}.reverse.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.room.name, reservation.room, :style => "text-decoration:none; color:#bce5ff;"  %></td>
        <td><%= reservation.valid_from.to_formatted_s(:long) %></td>
        <td><%= reservation.valid_to.to_formatted_s(:long) %></td>
        <td Style="text-align:center;"><font color="darkred">Expired</font></td>
      </tr>
    <% end %>
  </tbody>
</table><br>

app/views/reservations/new.html.erb
<div class="container" style="width:1200px">
  <div class="row" style="align-items:center">
    <div class="col-6"> 
      <h3>New reservation:</h3><br>
      <div class="card" style="width:550px">  
        <div class="container">
          <%= form_for @reservation, utl: {action: "create"} do |form| %>
            <br>
            <%= hidden_field_tag(:room_id, @room.id) %>
            
            <div class="field">
              <%= form.label :start_time%>: 
              <%= form.datetime_select :valid_from, default: 1.minute.from_now %>
            </div>

            <div class="field">
              <%= form.label :end_time %>: &nbsp;
              <%= form.datetime_select :valid_to, default: 31.minutes.from_now %>
            </div>
            <br>
            <div class="field">
              <%= form.label :attendants %>: 
              <%= form.number_field :attendants, min: 0, max: @room.max_capacity %>
            </div>
            <div style="float: right;">
              <%= form.submit "Confirm", class: 'btn btn-sm btn-success' %>
            </div>
            <br><br>
          <% end %>
        </div>
      </div> 
    </div>
    <div class="col-6">
      <br><br><br>
      <div class="card" style="width:370px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <div class="row" style="align-items:center">
            <div class="col-1">
              <% if @room.active %>
                <div><font color="green"><i class="far fa-check-circle fa-2x" title="The room is active"></i></font></div>
              <% else %>
                <div><font color="darkred"><i class="far fa-times-circle fa-2x" title="The room is inactive"></i></font></div>
              <% end %>
            </div>
            <div class="col-10">
                <h3 style="text-align:center"><strong><%= @room.name %></strong></h3>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="container">
            <div>Building: <strong><%= @room.building.name %></strong></div>
            <div>Floor: <strong><%= @room.floor %></strong></div>
            <div>Max capacity: <strong><%= @room.max_capacity %></strong></div>
            <div>Available equipment: 
              <ul>
                <% @room.accessories.each do |a|%>
                  <li><strong><%= a.name %></strong></li>
                <% end %>
              </ul>
            </div>
            <% @status = @room.status %>
            <div>Current status: 
            <% if @status.nil? %>
              <i><font color="yellow">There is no information for this room</font></i>
            <% elsif @status["is_occupied"] %>
              <strong><font color="darkred">The room is occupied</font></strong><br>
              Estimated occupants: <strong><%= @status["estimated_occupants"] %></strong>
           <% else %>
              <strong><font color="green">The room is available</font></strong>
            <% end %>
            </div><br>
            <div style="float: right;">
              <%= link_to 'Show', @room, class: 'btn btn-sm btn-primary' %>
            </div><br>
          </div>
        </div>  
      </div>
    </div>
  </div>
  <br><br>
  <%= link_to "Back", rooms_path, class: 'btn btn-sm btn-secondary'%>
  <%= link_to "My Reservations", reservations_path, class: 'btn btn-sm btn-primary'%>
</div>

app/views/reservations/show.html.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:1000px; text-align:center"><b>Reservation details</b></h5>
<br>
<div class="container" style="width:1000px">
  <div class="card" style="width:370px">
    <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
      <div class="row" style="align-items:center">
        <div class="col-1">
          <% if @room.active %>
            <div><font color="green"><i class="far fa-check-circle fa-2x" title="The room is active"></i></font></div>
          <% else %>
            <div><font color="darkred"><i class="far fa-times-circle fa-2x" title="The room is inactive"></i></font></div>
          <% end %>
        </div>
        <div class="col-10">
            <h3 style="text-align:center"><strong><%= @room.name %></strong></h3>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="container" style="margin-left:20px">
        <div>User: <strong><%= @reservation.user.name %></strong></div>
        <div>Building: <strong><%= @room.building.name %></strong></div>
        <div>Floor: <strong><%= @room.floor %></strong></div>
        <div>Available equipment: 
          <ul>
            <% @room.accessories.each do |a|%>
              <li><strong><%= a.name %></strong></li>
            <% end %>
          </ul>
        </div>
        <div>Max capacity: <strong><%= @room.max_capacity %></strong></div>
        <div>Expected attendants: <strong><%= @reservation.attendants %></strong></div><br>
        <div>Start time: <strong><%= @reservation.valid_from.to_formatted_s(:long) %></strong></div>
        <div>End time: <strong><%= @reservation.valid_to.to_formatted_s(:long) %></strong></div><br>
        <div style="float:right">
            <% if (current_user.is_admin? || current_user == @reservation.user) %>
              <%= link_to 'Cancel Reservation', @reservation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
            <% end %>
          </div>
      </div>
    </div>
  </div><br>
  <%= link_to "My Reservations", reservations_path, class: 'btn btn-sm btn-primary'%>
  <% if current_user.is_admin? %>
    <%= link_to 'Room info', @room, class: 'btn btn-sm btn-info' %>
  <% end %>
</div><br>