config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :accessories
  resources :rooms
  resources :buildings
  resources :users
  get '/occupancy', to: 'rooms#occupancy'
  get '/charts', to: 'reservations#charts'
  get '/all_reservations', to: 'reservations#all'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new' 
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  post '/schedule', to: 'reservations#schedule' 
  post '/reserve', to: 'reservations#reserve' 
  post '/switch_role', to: 'users#switch_role' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :building
	has_and_belongs_to_many :accessories
	has_many :reservations
	has_many :users, through: :reservations
	validates :name, presence: true
	validates :code, uniqueness: true
	paginates_per 15

	def is_active?
		self.active
	end

	def status
		response = Faraday.get "https://ca-3-api.mybluemix.net/api/v1/rooms/#{self.code}"
		#response.body
		output = case
			when response.status == 200 then JSON.parse(response.body)
			when response.status == 404 then nil
		end
	end	

	def self.without_active_reservation
		Room.all - Room.joins(:reservations).merge(Reservation.active)
	end

	def drop_down
		"#{self.name} - Floor: #{self.floor} - Max. capacity: #{self.max_capacity} - Equipment: #{self.accessories.map{|a| a.name}}"
	end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :verify_if_admin_and_redirect_with_error_message_if_not, only: [:new, :edit, :create, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms_selected_in_nav = true
    @paginated_rooms = if params[:building_id]
      Room.all.where(building_id: params[:building_id]).page params[:page]
    elsif params[:accessory_id]
      Room.joins(:accessories).where("accessory_id = ?", params[:accessory_id].to_i).page params[:page]
    elsif params[:floor]
      Room.all.where(floor: params[:floor]).page params[:page]
    else 
      Room.all.page params[:page]
    end
    @paginated_rooms = @paginated_rooms.where(active: true) unless current_user.is_admin?
    @rooms = if params[:q]
      @paginated_rooms.where('name LIKE ?', "%#{params[:q]}%")
    else
      @rooms = @paginated_rooms
    end
  end
  
  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
    @buildings = Building.all
    @equipment = Accessory.all
  end

  # GET /rooms/1/edit
  def edit
    @buildings = Building.all
    @equipment = Accessory.all
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        flash[:success] = "Room was successfully created."
        format.html { redirect_to @room }
        format.json { render :show, status: :created, location: @room }
      else
        flash[:danger] = "There was an error performing the operation. #{@room.errors.full_messages.first}"
        format.html { redirect_back fallback_location: rooms_path }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    if room_params[:active]!='1' && @room.reservations.not_expired.any?
      flash[:warning] = "Room is now deactivated. However all existing reservations will still be valid."
    end
    respond_to do |format|
      if @room.update(room_params)
        flash[:success] = "Room information was successfully updated."
        format.html { redirect_to @room }
        format.json { render :show, status: :ok, location: @room }
      else
        flash[:danger] = "There was an error performing the operation. #{@room.errors.full_messages.first}"
        format.html { redirect_back fallback_location: @room }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    if @room.reservations.scheduled.any?
      flash[:warning] = "A room with active reservations cannot be deleted."
      redirect_to @room
    else
    @room.destroy
      respond_to do |format|
        flash[:success] = "Room was successfully deleted."
        format.html { redirect_to rooms_url}
        format.json { head :no_content }
      end
    end
  end

  def occupancy
    @occupancy_selected_in_nav = true
    @rooms_reserved = Room.joins(:reservations).merge(Reservation.active)
    @rooms_not_reserved = Room.without_active_reservation
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      begin 
        @room = Room.find(params[:id])
        (if !@room.is_active? 
          flash[:danger] = "The room you are trying to access is not available"
          redirect_to rooms_url
        end) unless current_user.is_admin?
      rescue 
        flash[:danger] = "Room not found"
        redirect_to rooms_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :code, :floor, :max_capacity, :active, :building_id, accessory_ids:[])
    end

    def verify_if_admin_and_redirect_with_error_message_if_not 
      unless current_user.is_admin?
        flash[:danger] = "You are not authorized to perform this action."
        redirect_to rooms_url
      end 
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <div class="row">
    <div class="col-9">
      <%= form.label :name %><br>
      <%= form.text_field :name, size: 30 %>
    </div>
    <div class="col">
      <%= form.label :code %><br>
      <%= form.text_field :code, size: 3 %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-6">
      <%= form.label :building %><br>
      <%= form.collection_select(:building_id, @buildings, :id, :name) %>
    </div>
      <div class="col">
      <%= form.label :floor %><br>
      <%= form.number_field :floor %>
    </div>
    <div class="col">
      <%= form.label :max_capacity %><br>
      <%= form.number_field :max_capacity, min: 0 %>
    </div>
  </div><br>
  <div class="row">
    <div class="col">
    <div class="check-box checkbox-margin">
      <%= form.label :equipment %><br>
      <%= form.collection_check_boxes(:accessory_ids, @equipment, :id, :name) %>
    </div></div>
  </div><br>
  <div class="field">
    <%= form.label :active %> &nbsp; 
    <%= form.check_box :active %>
  </div>
  <div class="actions" style="float:right">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="col"> 
      <div class="card" style="width:550px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <h3 style="text-align:center">Edit room info</h3>
        </div>
        <div class="card-body">
          <div class="container">
            <%= render 'form', room: @room %>
          </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <%= link_to "Back", @room, class: 'btn btn-sm btn-secondary'%>
</div>

app/views/rooms/index.html.erb
<div class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7">
  <div class="row">
    <div class="col" style="text-align:right">
      <% if params[:q].present? %> 
        <h5 class="vertical-center"><b>Rooms results including "<%= params[:q] %>"</b></h5></div>
      <% else %>
        <h5 class="vertical-center"><b>Rooms</b></h5></div>
      <% end %>
    <div class="col" style="text-align:right; margin-top:3px">
      <%= form_tag(rooms_path, method: :get) do %>
        <%= text_field_tag :q %>
        <button type="submit" class="btn btn-sm"><i class="fa fa-search"></i></button>
      <% end %>
    </div>
  </div>
</div><br>
<div class="container">
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="card" style="width:220px; height:270px; margin-bottom:2px; margin:0 auto;">
        <a href="rooms/<%= room.id %>" style="text-decoration:none; color:#bce5ff;">
          <div class="card-header" style="width:220px; height:55px; background-color:rgba(0, 121, 203, 0.5);">
            <div class="row" style="align-items:center">
              <div class="col-2">
                <% if room.active %>
                  <div><font color="green"><i class="far fa-check-circle fa-2x" title="The room is active"></i></font></div>
                <% else %>
                  <div><font color="darkred"><i class="far fa-times-circle fa-2x" title="The room is inactive"></i></font></div>
                <% end %>
              </div>
              <div class="col-10">
                <% if room.name.size > 13 %>
                  <h5 style="font-size:1em; text-align:right"><strong><%= room.name %></strong></h5>
                <% else %>
                  <h5 style="text-align:center"><strong><%= room.name %></strong></h5>
                <% end %>
              </div>
            </div>
          </div>
        </a>  
        <div class="card-body" style="margin-left:5px">
          <div>Building: <strong><%= room.building.name %></strong></div>
          <div>Floor: 
            <strong>
              <a href="/rooms?floor=<%= room.floor %>" style="color:#bce5ff;">
                <strong><%= room.floor %></strong>
              </a>
            </strong>
          </div>
          <div>Max capacity: <strong><%= room.max_capacity %></strong></div>
          <% if current_user.is_admin? %>
            <% @status = room.status %>
            <div>Status:
              <% if @status.nil? %>
                <i><font color="yellow">No information</font></i>
              <% elsif @status["is_occupied"] %>
                <strong><font color="darkred">Occupied</font></strong><br>
            <% else %>
                <strong><font color="green">Available</font></strong>
              <% end %>
            </div>
          <% else %>
            <br>
          <% end %>
          <br>
          <div style="text-align:right">
          <%= link_to 'Reserve', new_reservation_path(room_id: room.id), class: 'btn btn-sm btn-primary' %></div>
        </div>
      </div>
    <% end %>
  </div><br><br>
  <div class="row">
    <div class="col">
      <% if current_user.is_admin? %>
        <div class="row">
          <%= link_to 'New Room', new_room_path, :class => "btn btn-sm btn-success" %> &nbsp;
        </div>
      <% end %>
    </div>
    <div class="col"><%= paginate @rooms %></div>
  </div>
</div><br>

app/views/rooms/new.html.erb
<br>
<div class="container" style="width:1000px">
  <div class="row" style="align-items:center">
    <div class="col"> 
      <div class="card" style="width:550px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <h3 style="text-align:center">New room</h3>
        </div>
        <div class="card-body">
          <div class="container">
            <%= render 'form', room: @room %>
          </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <%= link_to "Back", rooms_path, class: 'btn btn-sm btn-secondary'%>
</div>

app/views/rooms/occupancy.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:1080px; text-align:center"><b>Unoccupied rooms (reserved)</b></h5>
<div class="container" style="width:1080px;">
  <div class="row">
    <% @rooms_reserved.each do |room| %>
      <% @status = room.status %>
      <% if (!@status.nil? && !@status["is_occupied"]) %>
        <div class="card" style="width:350px; margin:0 auto; margin-bottom:10px">
          <a href="rooms/<%= room.id %>" style="text-decoration:none; color:#bce5ff;">
            <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
              <h3 style="text-align:center"><strong><%= room.name %></strong></h3>
            </div>
          </a>
          <a href="reservations/<%= room.reservations.active.first.id %>" style="text-decoration:none; color:#bce5ff;">
            <div class="card-body" style="margin-left:15px">
              <div>Reserved by: <strong><%= room.reservations.active.first.user.name %></strong></div>
              <div>Reserved from: <strong><%= room.reservations.active.first.valid_from.to_formatted_s(:long) %></strong></div>
              <div>Reserved until: <strong><%= room.reservations.active.first.valid_to.to_formatted_s(:long) %></strong></div>
              <div>Occupied: <strong><font color="yellow"><%= @status["is_occupied"] %></font></strong></div>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>
  </div>
</div><br>
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:1080px; text-align:center"><b>Occupied rooms (not reserved)</b></h5>
<div class="container" style="width:1080px;">
  <div class="row">
    <% @rooms_not_reserved.each do |room| %>
      <% @status = room.status %>
      <% if (!@status.nil? && @status["is_occupied"]) %>
        <a href="rooms/<%= room.id %>" style="text-decoration:none; color:#bce5ff; margin:0 auto;">
          <div class="card" style="width:250px; margin-bottom:15px">
            <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
              <h4 style="text-align:center"><strong><%= room.name %></strong></h4>
            </div>
            <div class="card-body" style="text-align:center">
              <div>Estimated occupants: <strong><font color="yellow"><%= @status["estimated_occupants"] %></font></strong></div>
            </div>
          </div>
        </a>
      <% end %>
    <% end %>
  </div>
</div><br>

app/views/rooms/show.html.erb
<h5 class="container" style="background-color: #bce5ff; color:#42698f; opacity:0.7; width:1000px; text-align:center"><b>Room details</b></h5>
<br>
<div class="container" style="width:980px">
  <div class="row" style="align-items:center">
    <div class="col">
      <div class="card" style="width:370px">
        <div class="card-header" style="background-color:rgba(0, 121, 203, 0.5);">
          <div class="row" style="align-items:center">
            <div class="col-1">
              <% if @room.active %>
                <div><font color="green"><i class="far fa-check-circle fa-2x" title="The room is active"></i></font></div>
              <% else %>
                <div><font color="darkred"><i class="far fa-times-circle fa-2x" title="The room is inactive"></i></font></div>
              <% end %>
            </div>
            <div class="col-10">
                <h3 style="text-align:center"><strong><%= @room.name %></strong></h3>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="container">
            <div>Code: <strong><%= @room.code %></strong></div>
            <div>Building: <strong><%= @room.building.name %></strong></div>
            <div>Floor: <strong><%= @room.floor %></strong></div>
            <div>Max capacity: <strong><%= @room.max_capacity %></strong></div>
            <div>Available equipment: 
              <ul>
                <% @room.accessories.each do |a|%>
                  <li><strong><%= a.name %></strong></li>
                <% end %>
              </ul>
            </div>
            <% @status = @room.status %>
            <div>Current status: 
            <% if @status.nil? %>
              <i><font color="yellow">There is no information for this room</font></i>
            <% elsif @status["is_occupied"] %>
              <strong><font color="darkred">The room is occupied</font></strong><br>
              Estimated occupants: <strong><%= @status["estimated_occupants"] %></strong>
           <% else %>
              <strong><font color="green">The room is available</font></strong>
            <% end %>
            </div><br><br>
            <div style="float:right">
              <%= link_to 'Reserve', new_reservation_path(room_id: @room.id), class: 'btn btn-sm btn-primary' %>
              <% if current_user.is_admin? %>
                <%= link_to 'Edit', edit_room_path(@room), class: 'btn btn-sm btn-info' %>
                <%= link_to 'Delete', @room, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
              <% end %>
            </div><br>
          </div>
        </div>
      </div>
    </div>
    <% if @room.reservations.not_expired.any? %>
      <div class="col">
        <div class="card" style="width:530px">
          <h4 class="card-header" style="background-color:rgba(0, 121, 203, 0.5);"> &nbsp; Scheduled reservations:</h4>
          <div class="card-body">
            <ul><font size="2.5">
            <% @room.reservations.not_expired.sort_by {|item| item.valid_from}.take(10).each do |r| %>
              <li>From <%= r.valid_from %> - To <%= r.valid_to %></li>
            <% end %>
            </font></ul>
          </div>
        </div>
      </div>
    <% end %>
  </div><br>
  <%= link_to "Rooms list", rooms_path, class: 'btn btn-sm btn-primary'%>
</div>